/**
 * After `STATIC=1 next build`, writes what a static host needs and Next cannot emit:
 * out/_headers for security and caching, and out/_redirects for the canonical host.
 */
import { copyFileSync, existsSync, writeFileSync } from "node:fs";

const OUT = "out";
if (!existsSync(OUT)) {
  console.error("No out/ directory. Run: npm run build:static");
  process.exit(1);
}

// Next writes the social image without an extension, which a static host would serve as a download.
// Keep a .png copy and force the type on the extensionless path that the meta tag points at.
if (existsSync(`${OUT}/opengraph-image`)) copyFileSync(`${OUT}/opengraph-image`, `${OUT}/opengraph-image.png`);

writeFileSync(`${OUT}/_headers`, `# generated by scripts/static-extras.mjs
/opengraph-image
  Content-Type: image/png
  Cache-Control: public, max-age=86400

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
  Permissions-Policy: camera=(), microphone=(), geolocation=()
  Strict-Transport-Security: max-age=63072000; includeSubDomains

/_next/static/*
  Cache-Control: public, max-age=31536000, immutable
`);

/**
 * No _redirects file is written. Cloudflare's asset server only accepts relative rules there, and
 * an absolute one is skipped silently, so sending www to the apex belongs in a Redirect Rule in
 * the Cloudflare dashboard instead.
 */

console.log("Wrote out/_headers");
